name: test_satoripop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # UI/UX
  provider: ^6.0.5
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6

  # LANGUAGE
  intl: ^0.18.0
  flag: ^6.0.0

  # NETWORKING & STORAGE
  http: ^0.13.5
  http_parser: ^4.0.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  path_provider: ^2.1.3
  animated_splash_screen: ^1.3.0
  # MEDIA
  mime: ^1.0.4
  image_picker: ^0.8.7
  file_picker: ^5.3.0
  rive: ^0.12.4

  # slide
  flutter_slidable: ^3.1.0
  slideable: ^0.0.2
  # Charts
  syncfusion_flutter_gauges: ^25.2.3

  switcher: ^1.0.0
  # OTHERS
  collection: any
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Caladea
      fonts:
        - asset: assets/fonts/Caladea-Regular.ttf

